version: '2'
services:
  postgres-server:    # The Postgres Database Service
    image: postgres:12.2
    restart: always
    container_name: zabbix-db
    environment:   # Username, password and database name variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix-bdd-password
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata #data storage
    volumes:
      - /apps/zabbix/db:/var/lib/postgresql/data

  zabbix-server:     # The main Zabbix Server Software Service
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    restart: always
    container_name: zabbix
    environment:   # The Postgres database value variable
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix-bdd-password
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_STARTVMWARECOLLECTORS: 10
      ZBX_VMWAREFREQUENCY: 30
      ZBX_VMWAREPERFFREQUENCY: 30
      ZBX_VMWARECACHESIZE: 16M
      ZBX_VMWARETIMEOUT: 10
    depends_on:
      - postgres-server
    ports:
      - 10051:10051
    volumes:  # Volumes for scripts and related files you can add
      - /apps/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      
  zabbix-web:    # The main Zabbix web UI or interface
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    restart: always
    container_name: zabbix-web
    environment:  # Postgre database variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix-bdd-password
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server  # Zabbix related and Php variables
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Paris"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:    # Port where Zabbix UI is available
      - 8090:8080

  grafana-xxl:  #optional more functional and creative UI
    image: monitoringartist/grafana-xxl:latest
    restart: always
    container_name: grafana
#    volumes: 
#      - /apps/grafana/config:/etc/grafana
#      - /apps/grafana/data:/var/lib/grafana
    environment:
#      - GF_PATHS_DATA=/config/data
#      - GF_PATHS_LOGS=/config/logs
#      - GF_PATHS_PLUGINS=/config/plugins
      - UPGRADEALL=false
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    ports:
      - 3000:3000
